# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    kernelPackages = pkgs.linuxPackages_xanmod_latest; # install custom xanmod kernel
    initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
    initrd.kernelModules = [];
    kernelModules = [ "kvm-intel" "v4l2loopback" "snd-aloop"];
    extraModulePackages = with config.boot.kernelPackages; [ rtl88x2bu v4l2loopback.out ];
    extraModprobeConfig = ''
      options vl42loopback exclusive_caps=1 card_label="Virtual Camera"
    ''; # setup virtual cam
  };

  hardware = {
    enableAllFirmware = true;
    enableRedistributableFirmware = true;

    opengl = {
        enable = true;
        driSupport = true;
        driSupport32Bit = true;
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d380c93c-4ebb-48df-9cd3-3e2fa1424605";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8695-9BAA";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
